// <auto-generated />
using System;
using DemokrataTT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemokrataTT.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemokrataTT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirdDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondSurName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirdDate = new DateTime(1922, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2024, 3, 16, 22, 48, 29, 610, DateTimeKind.Local).AddTicks(9185),
                            FirstName = "Orfelina",
                            LastName = "Sanchez",
                            ModificationDate = new DateTime(2024, 3, 16, 22, 48, 29, 610, DateTimeKind.Local).AddTicks(9194),
                            Salary = 100,
                            SecondName = "Maria",
                            SecondSurName = "Rueda"
                        },
                        new
                        {
                            Id = 2,
                            BirdDate = new DateTime(1910, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationDate = new DateTime(2024, 3, 16, 22, 48, 29, 610, DateTimeKind.Local).AddTicks(9197),
                            FirstName = "Olegario",
                            LastName = "Ceron",
                            ModificationDate = new DateTime(2024, 3, 16, 22, 48, 29, 610, DateTimeKind.Local).AddTicks(9197),
                            Salary = 100,
                            SecondName = "Jose",
                            SecondSurName = "Camacho"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
